### PR TITLE
implement fixes for two memory leaks

### LINKED ISSUE #116: [todo] re-check current debug build for memory leaks
my latest debug build execution had two memory leaks listed, analyze where they originate

### PR DESCRIPTION
**Pull request by carfesh**
fixes #116

### CODE REVIEW

File: fellow/SRC/WinFellow/VirtualHost/CoreFactory.cpp [hunk 1]
```diff
@@ -33,6 +33,9 @@ void CoreFactory::DestroyServices()
 
   delete _core.Log;
   _core.Log = nullptr;
+
+  delete _core.FileInformation;
+  _core.Log = nullptr;
```
Comment (petschau) [inline fellow/SRC/WinFellow/VirtualHost/CoreFactory.cpp:38]:
```suggestion
  _core.FileInformation = nullptr;
```
